server:
  port: 8080

school:
  name: sxt
  addr: ${school.name}


#自定义静态资源的一个路径配置，有多个用,分割。一旦修改了配置，默认的配置就被修改了
#spring:
#  resources:
#    static-locations: classpath:/jingtai/

spring:
  servlet:
    multipart:
      #配置单个上传文件的大小限制
      max-file-size: 2MB
      #配置在一次请求中上传文件的总容量的限制
      max-request-size: 10MB